repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        files: ^sancho_.*\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        args: [--fix]
        files: ^sancho_.*\.py$

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        files: ^sancho_.*\.py$
