usb_cam_node:
  ros__parameters:
    video_device: "/dev/video0"
    image_width: 1280
    image_height: 720
    framerate: 15  # Baja tasa de frames para menos carga de CPU
    pixel_format: yuyv  # <<--- SIN compresión
    camera_name: "sancho_camera"
    camera_info_url: "package://sancho_bringup/config/camera_info_high.yaml"

    # Controles Manuales
    brightness: 128
    contrast: 32
    saturation: 32
    sharpness: 32

    # Desactivar automáticos
    auto_focus: false
    focus_absolute: 0
    auto_exposure: false
    exposure_absolute: 200
    auto_white_balance: false
    white_balance_temperature: 4500
