slam_toolbox:
  ros__parameters:
    use_sim_time: False
    scan_topic: "/scan_1st"
    base_frame: "base_footprint"
    odom_frame: "odom"
    map_frame: "map"
    debug_logging: true
    transform_timeout: 2.0  # sube el tiempo permitido para TFs
    stamp_timeout: 2.0      # sube el tiempo permitido para scans desincronizados
    mode: "mapping"
