name: Lint Sancho Packages

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install tools
        run: |
          pip install black ruff pylint

      - name: Lint all src/sancho_*/sancho_* packages
        run: |
          set -e  # hace que el job falle si cualquier comando falla
          
          for pkg in src/sancho_*/sancho_*; do
           
            echo "🔍 Pylint (calidad mínima 7)"
            pylint "$pkg" --fail-under=7.0
          done
